"""Issue creation screen — pre-fills from code findings, lets user edit & submit."""

import asyncio
import os
from typing import Optional

from textual import on
from textual.app import ComposeResult
from textual.containers import Center, Vertical, VerticalScroll
from textual.screen import Screen
from textual.widgets import Button, Footer, Header, Input, Label, Markdown, Static, TextArea

from repo_inspector.fetcher import GitHubFetcher
from repo_inspector.models import InspectionResult


def _build_issue_body(result: InspectionResult) -> str:
    """Generate a markdown issue body from code analysis findings."""
    lines: list[str] = []
    lines.append("## Repo Inspector — Code Analysis Findings\n")
    lines.append(f"**Repository:** {result.repo}")
    lines.append(f"**Period:** {result.timeframe.label}")
    lines.append(f"**Generated:** {result.generated_at:%Y-%m-%d %H:%M UTC}\n")

    c = result.code
    lines.append(f"**Total findings:** {c.total_findings} "
                 f"({c.security_findings} security, {c.refactoring_findings} refactoring)\n")

    if c.llm_summary:
        lines.append(f"> {c.llm_summary}\n")

    for fa in c.folders:
        if not fa.findings:
            continue
        lines.append(f"### 📁 {fa.path}/\n")
        for f in fa.findings:
            lines.append(f"- {f.display_severity} **{f.title}** (`{f.category}`)")
            lines.append(f"  {f.description}")
            if f.suggestion:
                lines.append(f"  ✅ *Fix:* {f.suggestion}")
            lines.append("")

    lines.append("---")
    lines.append("*Generated by [repo-inspector](https://github.com/your-org/repo-inspector)*")
    return "\n".join(lines)


class IssueScreen(Screen):
    """Screen for reviewing and submitting a GitHub issue."""

    CSS = """
    IssueScreen {
        layout: vertical;
    }
    #issue-container {
        padding: 1 2;
    }
    #issue-title-input {
        margin: 1 0;
    }
    #issue-body-area {
        height: 1fr;
        min-height: 20;
        margin: 1 0;
    }
    #issue-actions {
        height: 4;
        align: center middle;
        margin: 1 0;
    }
    #issue-status {
        text-align: center;
        margin: 1 0;
    }
    """

    BINDINGS = [
        ("escape", "go_back", "Back"),
    ]

    def __init__(self, result: InspectionResult, **kwargs) -> None:  # type: ignore[no-untyped-def]
        super().__init__(**kwargs)
        self.result = result
        self._default_title = f"[repo-inspector] Code analysis findings for {result.repo}"
        self._default_body = _build_issue_body(result)

    def compose(self) -> ComposeResult:
        yield Header(show_clock=True)
        with VerticalScroll(id="issue-container"):
            yield Static("📝  Create Issue on GitHub", classes="section-title")
            yield Label(f"Repository: {self.result.repo}")
            yield Label("")
            yield Label("Issue Title:")
            yield Input(value=self._default_title, id="issue-title-input")
            yield Label("Issue Body (edit as needed):")
            yield TextArea(self._default_body, id="issue-body-area", language="markdown")
            yield Label("", id="issue-status")
            from textual.containers import Horizontal
            with Horizontal(id="issue-actions"):
                yield Button("✅  Submit Issue", id="submit-issue-btn", variant="success")
                yield Button("Cancel", id="cancel-issue-btn", variant="default")
        yield Footer()

    @on(Button.Pressed, "#submit-issue-btn")
    async def submit_issue(self) -> None:
        title_input = self.query_one("#issue-title-input", Input)
        body_area = self.query_one("#issue-body-area", TextArea)
        status_label = self.query_one("#issue-status", Label)

        title = title_input.value.strip()
        body = body_area.text.strip()

        if not title:
            status_label.update("⚠  Title cannot be empty")
            return

        status_label.update("⏳  Creating issue …")

        token = os.environ.get("GITHUB_TOKEN", "")
        if not token:
            status_label.update("⚠  GITHUB_TOKEN not set — cannot create issue")
            return

        parts = self.result.repo.split("/")
        owner, repo = parts[0], parts[1]

        try:
            fetcher = GitHubFetcher(token=token)
            result = await fetcher.create_issue(
                owner, repo, title, body,
                labels=["repo-inspector"],
            )
            await fetcher.close()
            issue_url = result.get("html_url", "")
            status_label.update(f"✅  Issue created: {issue_url}")
        except Exception as e:
            status_label.update(f"❌  Failed: {e}")

    @on(Button.Pressed, "#cancel-issue-btn")
    def cancel(self) -> None:
        self.app.pop_screen()

    def action_go_back(self) -> None:
        self.app.pop_screen()
